import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";

const red_hat_display = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-redhat",
});

const milk_honey = localfont({
  src: [
    {
      path: "../../public/fonts/MilkHoney.ttf",
      weight: "300"
    },
 
  ],
  variable: "--font-milk-honey",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${red_hat_display.variable} ${milk_honey.variable}`}>{children}</body>
    </html>
  );
}
